spring:
  application:
    name: ecoserver
  profiles:
    group:
      local:
        - local
        - jwt
        - oauth
      ci:
        - ci
        - jwt
        - oauth
      deploy:
        - deploy
        - jwt
        - oauth
    active: local
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0 # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      max-file-size: 104857600 # 한개 파일의 최대 사이즈 100MB (default: 1MB)
      max-request-size: 104857600 # 한개 요청의 최대 사이즈 100MB (default: 10MB)

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json

cloud:
  aws:
    cloudfront:
      domain: images.e-co.rldnd.net
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
