spring:
  config:
    activate:
      on-profile: "ci"

  application:
    name: ecoserver-ci

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      mode: always # mode: app 시작 시 data.sql에 작성된 코드로 database를 초기화 하도록 지정

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create #update
    defer-datasource-initialization: true #애플리케이션이 실행될 때 db를 초기화하지 않고 첫 데이터베이스 액세스 시 초기화를 수행
    generate-ddl: true

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG
