spring:
  application:
    name: ecoserver

  profiles:
    group:
      local:
        - local
        - jwt
        - oauth
      ci:
        - ci
        - jwt
        - oauth
      deploy:
        - deploy
        - jwt
        - oauth
    active: deploy

  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
