spring:
    application:
        name: ecoserver

    profiles:
        group:
            "local" : "local, jwt, oauth"
        active: local

    logging:
        level:
            org.springframework: DEBUG
            org.hibernate: DEBUG
